-- 02_schema.sql 业务表
-- 用户表
CREATE TABLE `user` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
  `username` VARCHAR(50) NOT NULL COMMENT '用户名/学号',
  `password` VARCHAR(100) NOT NULL COMMENT '密码',
  `name` VARCHAR(30) COMMENT '真实姓名',
  `phone` VARCHAR(20) COMMENT '手机号',
  `status` TINYINT DEFAULT 1 COMMENT '状态 1正常 0禁用',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT DEFAULT 0 COMMENT '逻辑删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

-- 自习室表
CREATE TABLE `study_room` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `room_name` VARCHAR(100) NOT NULL COMMENT '自习室名称',
  `location` VARCHAR(200) COMMENT '位置描述',
  `total_seat` INT NOT NULL COMMENT '总座位数',
  `status` TINYINT DEFAULT 1 COMMENT '1启用 0关闭',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='自习室';

-- 座位表
CREATE TABLE `seat` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `room_id` BIGINT NOT NULL COMMENT '自习室id',
  `seat_no` VARCHAR(30) NOT NULL COMMENT '座位编号',
  `status` TINYINT DEFAULT 1 COMMENT '1空闲 2占用 3维护',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT DEFAULT 0,
  UNIQUE KEY uk_room_seat (`room_id`,`seat_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='座位';

-- 预约记录表
CREATE TABLE `reservation` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `user_id` BIGINT NOT NULL COMMENT '用户id',
  `seat_id` BIGINT NOT NULL COMMENT '座位id',
  `start_time` DATETIME NOT NULL COMMENT '预约开始时间',
  `end_time` DATETIME NOT NULL COMMENT '预约结束时间',
  `sign_in_time` DATETIME NULL COMMENT '签到时间',
  `status` TINYINT NOT NULL COMMENT '0待签到 1已签到 2已取消 3超时释放',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='座位预约记录';